name: dl
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.12
  - pip
  - pytorch>=2.5
  - torchaudio>=2.5
  - numpy
  - pandas
  - scikit-learn
  - librosa
  - pyyaml
  - tqdm
  - matplotlib
  - tensorboard
  - huggingface_hub
  - pip:
      - mambapy>=1.2.0
      - sounddevice>=0.5
      - transformers>=4.51
